
import { TeamOption, Player } from './types';

export const TEAMS: TeamOption[] = [
  { name: 'Chennai Super Kings', short: 'CSK', color: '#F9CD05' },
  { name: 'Sunrisers Hyderabad', short: 'SRH', color: '#F78F2E' },
  { name: 'Mumbai Indians', short: 'MI', color: '#004BA0' },
  { name: 'Rajasthan Royals', short: 'RR', color: '#EA1A85' },
  { name: 'Delhi Capitals', short: 'DC', color: '#00008B' },
  { name: 'Royal Challengers Bengaluru', short: 'RCB', color: '#EC1C24' },
  { name: 'Kolkata Knight Riders', short: 'KKR', color: '#3A225D' },
  { name: 'Punjab Kings', short: 'PBKS', color: '#DD1F2D' },
  { name: 'Lucknow Super Giants', short: 'LSG', color: '#3CDCA0' },
  { name: 'Gujarat Titans', short: 'GT', color: '#1B2133' },
];

export const TOTAL_OVERS = 20;

// Updated 2025 Squad Data based on provided list
export const STATIC_SQUADS: Record<string, Omit<Player, 'id'>[]> = {
  CSK: [
    { name: "Ruturaj Gaikwad", role: "Batsman", battingSkill: 92, bowlingSkill: 10 },
    { name: "Devon Conway", role: "Batsman", battingSkill: 90, bowlingSkill: 5 },
    { name: "Rahul Tripathi", role: "Batsman", battingSkill: 85, bowlingSkill: 5 },
    { name: "Shivam Dube", role: "All-rounder", battingSkill: 89, bowlingSkill: 65 },
    { name: "Ravindra Jadeja", role: "All-rounder", battingSkill: 86, bowlingSkill: 90 },
    { name: "MS Dhoni", role: "Wicketkeeper", battingSkill: 85, bowlingSkill: 5 },
    { name: "R. Ashwin", role: "All-rounder", battingSkill: 75, bowlingSkill: 92 },
    { name: "Sam Curran", role: "All-rounder", battingSkill: 84, bowlingSkill: 88 },
    { name: "Matheesha Pathirana", role: "Bowler", battingSkill: 10, bowlingSkill: 95 },
    { name: "Khaleel Ahmed", role: "Bowler", battingSkill: 10, bowlingSkill: 88 },
    { name: "Noor Ahmad", role: "Bowler", battingSkill: 10, bowlingSkill: 89 },
  ],
  SRH: [
    { name: "Travis Head", role: "Batsman", battingSkill: 94, bowlingSkill: 20 },
    { name: "Abhishek Sharma", role: "All-rounder", battingSkill: 89, bowlingSkill: 65 },
    { name: "Heinrich Klaasen", role: "Batsman", battingSkill: 96, bowlingSkill: 5 },
    { name: "Nitish Kumar Reddy", role: "All-rounder", battingSkill: 85, bowlingSkill: 80 },
    { name: "Ishan Kishan", role: "Wicketkeeper", battingSkill: 88, bowlingSkill: 5 },
    { name: "Wiaan Mulder", role: "All-rounder", battingSkill: 80, bowlingSkill: 82 },
    { name: "Pat Cummins", role: "Bowler", battingSkill: 70, bowlingSkill: 94 },
    { name: "Mohammed Shami", role: "Bowler", battingSkill: 15, bowlingSkill: 93 },
    { name: "Harshal Patel", role: "Bowler", battingSkill: 30, bowlingSkill: 88 },
    { name: "Jaydev Unadkat", role: "Bowler", battingSkill: 25, bowlingSkill: 82 },
    { name: "Rahul Chahar", role: "Bowler", battingSkill: 15, bowlingSkill: 85 },
  ],
  MI: [
    { name: "Rohit Sharma", role: "Batsman", battingSkill: 93, bowlingSkill: 15 },
    { name: "Suryakumar Yadav", role: "Batsman", battingSkill: 98, bowlingSkill: 5 },
    { name: "Tilak Varma", role: "Batsman", battingSkill: 88, bowlingSkill: 20 },
    { name: "Hardik Pandya", role: "All-rounder", battingSkill: 90, bowlingSkill: 85 },
    { name: "Sherfane Rutherford", role: "Batsman", battingSkill: 85, bowlingSkill: 20 },
    { name: "Mitchell Santner", role: "All-rounder", battingSkill: 75, bowlingSkill: 88 },
    { name: "Jonny Bairstow", role: "Wicketkeeper", battingSkill: 89, bowlingSkill: 5 },
    { name: "Shardul Thakur", role: "Bowler", battingSkill: 60, bowlingSkill: 85 },
    { name: "Jasprit Bumrah", role: "Bowler", battingSkill: 25, bowlingSkill: 99 },
    { name: "Trent Boult", role: "Bowler", battingSkill: 30, bowlingSkill: 92 },
    { name: "Deepak Chahar", role: "Bowler", battingSkill: 40, bowlingSkill: 88 },
  ],
  RR: [
    { name: "Yashasvi Jaiswal", role: "Batsman", battingSkill: 92, bowlingSkill: 10 },
    { name: "Vaibhav Suryavanshi", role: "Batsman", battingSkill: 75, bowlingSkill: 10 },
    { name: "Shimron Hetmyer", role: "Batsman", battingSkill: 88, bowlingSkill: 5 },
    { name: "Riyan Parag", role: "All-rounder", battingSkill: 88, bowlingSkill: 75 },
    { name: "Dhruv Jurel", role: "Wicketkeeper", battingSkill: 85, bowlingSkill: 5 },
    { name: "Sanju Samson", role: "Wicketkeeper", battingSkill: 90, bowlingSkill: 5 },
    { name: "Sandeep Sharma", role: "Bowler", battingSkill: 10, bowlingSkill: 88 },
    { name: "Wanindu Hasaranga", role: "All-rounder", battingSkill: 75, bowlingSkill: 92 },
    { name: "Jofra Archer", role: "Bowler", battingSkill: 40, bowlingSkill: 94 },
    { name: "Fazalhaq Farooqi", role: "Bowler", battingSkill: 10, bowlingSkill: 88 },
    { name: "Maheesh Theekshana", role: "Bowler", battingSkill: 15, bowlingSkill: 89 },
  ],
  DC: [
    { name: "Jake Fraser-McGurk", role: "Batsman", battingSkill: 88, bowlingSkill: 5 },
    { name: "KL Rahul", role: "Wicketkeeper", battingSkill: 92, bowlingSkill: 5 },
    { name: "Abishek Porel", role: "Batsman", battingSkill: 80, bowlingSkill: 5 },
    { name: "Tristan Stubbs", role: "Wicketkeeper", battingSkill: 89, bowlingSkill: 10 },
    { name: "Axar Patel", role: "All-rounder", battingSkill: 85, bowlingSkill: 90 },
    { name: "Ashutosh Sharma", role: "Batsman", battingSkill: 84, bowlingSkill: 5 },
    { name: "Faf du Plessis", role: "Batsman", battingSkill: 88, bowlingSkill: 5 },
    { name: "Kuldeep Yadav", role: "Bowler", battingSkill: 20, bowlingSkill: 94 },
    { name: "Mitchell Starc", role: "Bowler", battingSkill: 30, bowlingSkill: 93 },
    { name: "Mukesh Kumar", role: "Bowler", battingSkill: 10, bowlingSkill: 86 },
    { name: "T. Natarajan", role: "Bowler", battingSkill: 10, bowlingSkill: 89 },
  ],
  RCB: [
    { name: "Virat Kohli", role: "Batsman", battingSkill: 98, bowlingSkill: 10 },
    { name: "Phil Salt", role: "Wicketkeeper", battingSkill: 90, bowlingSkill: 5 },
    { name: "Rajat Patidar", role: "Batsman", battingSkill: 87, bowlingSkill: 5 },
    { name: "Liam Livingstone", role: "All-rounder", battingSkill: 91, bowlingSkill: 75 },
    { name: "Tim David", role: "Batsman", battingSkill: 88, bowlingSkill: 10 },
    { name: "Krunal Pandya", role: "All-rounder", battingSkill: 80, bowlingSkill: 85 },
    { name: "Jitesh Sharma", role: "Wicketkeeper", battingSkill: 84, bowlingSkill: 5 },
    { name: "Josh Hazlewood", role: "Bowler", battingSkill: 20, bowlingSkill: 93 },
    { name: "Bhuvneshwar Kumar", role: "Bowler", battingSkill: 35, bowlingSkill: 90 },
    { name: "Yash Dayal", role: "Bowler", battingSkill: 10, bowlingSkill: 85 },
    { name: "Nuwan Thushara", role: "Bowler", battingSkill: 10, bowlingSkill: 88 },
  ],
  KKR: [
    { name: "Quinton de Kock", role: "Wicketkeeper", battingSkill: 89, bowlingSkill: 5 },
    { name: "Sunil Narine", role: "All-rounder", battingSkill: 88, bowlingSkill: 92 },
    { name: "Venkatesh Iyer", role: "All-rounder", battingSkill: 86, bowlingSkill: 60 },
    { name: "Ajinkya Rahane", role: "Batsman", battingSkill: 85, bowlingSkill: 5 },
    { name: "Rinku Singh", role: "Batsman", battingSkill: 91, bowlingSkill: 5 },
    { name: "Andre Russell", role: "All-rounder", battingSkill: 92, bowlingSkill: 86 },
    { name: "Ramandeep Singh", role: "All-rounder", battingSkill: 78, bowlingSkill: 75 },
    { name: "Varun Chakravarthy", role: "Bowler", battingSkill: 10, bowlingSkill: 90 },
    { name: "Harshit Rana", role: "Bowler", battingSkill: 25, bowlingSkill: 86 },
    { name: "Vaibhav Arora", role: "Bowler", battingSkill: 15, bowlingSkill: 82 },
    { name: "Anrich Nortje", role: "Bowler", battingSkill: 20, bowlingSkill: 92 },
  ],
  PBKS: [
    { name: "Prabhsimran Singh", role: "Batsman", battingSkill: 85, bowlingSkill: 5 },
    { name: "Shreyas Iyer", role: "Batsman", battingSkill: 91, bowlingSkill: 10 },
    { name: "Shashank Singh", role: "Batsman", battingSkill: 87, bowlingSkill: 20 },
    { name: "Glenn Maxwell", role: "All-rounder", battingSkill: 90, bowlingSkill: 75 },
    { name: "Marcus Stoinis", role: "All-rounder", battingSkill: 89, bowlingSkill: 80 },
    { name: "Josh Inglis", role: "Wicketkeeper", battingSkill: 86, bowlingSkill: 5 },
    { name: "Marco Jansen", role: "All-rounder", battingSkill: 75, bowlingSkill: 88 },
    { name: "Arshdeep Singh", role: "Bowler", battingSkill: 15, bowlingSkill: 92 },
    { name: "Yuzvendra Chahal", role: "Bowler", battingSkill: 10, bowlingSkill: 93 },
    { name: "Xavier Bartlett", role: "Bowler", battingSkill: 20, bowlingSkill: 85 },
    { name: "Harpreet Brar", role: "All-rounder", battingSkill: 60, bowlingSkill: 84 },
  ],
  LSG: [
    { name: "Rishabh Pant", role: "Wicketkeeper", battingSkill: 93, bowlingSkill: 10 },
    { name: "Mitchell Marsh", role: "All-rounder", battingSkill: 89, bowlingSkill: 82 },
    { name: "Aiden Markram", role: "Batsman", battingSkill: 86, bowlingSkill: 40 },
    { name: "Nicholas Pooran", role: "Wicketkeeper", battingSkill: 92, bowlingSkill: 5 },
    { name: "David Miller", role: "Batsman", battingSkill: 88, bowlingSkill: 5 },
    { name: "Abdul Samad", role: "Batsman", battingSkill: 82, bowlingSkill: 10 },
    { name: "Ayush Badoni", role: "Batsman", battingSkill: 83, bowlingSkill: 10 },
    { name: "Avesh Khan", role: "Bowler", battingSkill: 15, bowlingSkill: 87 },
    { name: "Mohsin Khan", role: "Bowler", battingSkill: 20, bowlingSkill: 86 },
    { name: "Mayank Yadav", role: "Bowler", battingSkill: 15, bowlingSkill: 91 },
    { name: "Ravi Bishnoi", role: "Bowler", battingSkill: 15, bowlingSkill: 90 },
  ],
  GT: [
    { name: "Shubman Gill", role: "Batsman", battingSkill: 95, bowlingSkill: 5 },
    { name: "Jos Buttler", role: "Wicketkeeper", battingSkill: 94, bowlingSkill: 5 },
    { name: "Sai Sudharsan", role: "Batsman", battingSkill: 90, bowlingSkill: 5 },
    { name: "Shahrukh Khan", role: "Batsman", battingSkill: 85, bowlingSkill: 10 },
    { name: "Rahul Tewatia", role: "All-rounder", battingSkill: 84, bowlingSkill: 70 },
    { name: "Washington Sundar", role: "All-rounder", battingSkill: 80, bowlingSkill: 85 },
    { name: "Rashid Khan", role: "All-rounder", battingSkill: 75, bowlingSkill: 96 },
    { name: "Mohammed Siraj", role: "Bowler", battingSkill: 20, bowlingSkill: 90 },
    { name: "Prasidh Krishna", role: "Bowler", battingSkill: 15, bowlingSkill: 88 },
    { name: "Kagiso Rabada", role: "Bowler", battingSkill: 30, bowlingSkill: 93 },
    { name: "Gerald Coetzee", role: "Bowler", battingSkill: 35, bowlingSkill: 89 },
  ],
};
